### ISSUE TITLE
Unexpected number of traffic lanes

### ISSUE THREAD

**Issue by enzet** [a-b-street/osm2lanes#1]
The last test in A/B Street has the following specification:

```rust
            (
                "https://www.openstreetmap.org/way/335668924",
                vec!["lanes=1", "sidewalk=none"],
                DrivingSide::Right,
                "SddS",
                "vv^^",
            ),
```

Why do we assume two traffic lanes here?

**Comment by dabreegster** [comment]
Ah, great question. What does `lanes=1` without `oneway=yes` mean? In practice, I suspect this alleyway is too narrow to allow two vehicles to pass each other. Either there's room for one to pull off to the side temporarily or one of them just has to reverse out of the alley. What's the ideal way to represent this?

A/B Street currently just pretends there's one lane each direction and ignores `lanes=1`. The lane width guessed is hopefully narrow. Another oddity here is that `sidewalk=none` translates into the "shoulder" lane for walking on either side. Both of these choices are very questionable. What should this common library / specification do for this case of a narrow alleyway without explicit one-way restrictions?

**Comment by enzet** [comment]
Yeah, makes sense. So, the general rule is we ignore number of lanes if it's less than two and no `oneway=yes` is specified? 

Good questions about sidewalks and lanes. Maybe we have to make these features optional? So that user can control the result?

And anyway I think we should compute explanation for the assumptions we made about lane number as well as about shoulder lanes and add them into the lane specification.

**Comment by enzet** [comment]
Now all tests from A/B Street pass.

**Comment by dabreegster** [comment]
> So, the general rule is we ignore number of lanes if it's less than two and no oneway=yes is specified?

Correct. That's a much simpler summary of the current implementation in Rust: https://github.com/a-b-street/abstreet/blob/81af2625116cb7c710ab52d85c224083c37459a0/map_model/src/make/initial/lane_specs.rs#L92

> Maybe we have to make these features optional? So that user can control the result?

I think so. We could omit this type of behavior entirely, but then a caller has to detect these edge case situations anyway.

If the user doesn't enable the feature for this case, what's the correct output for this example? Just a single general-purpose lane in one direction, meaning we assume `oneway=yes`?

> compute explanation for the assumptions we made about lane number as well as about shoulder lanes and add them into the lane specification.

Definitely. I like the `source` field that @tordans mocked up in the discussion

**Comment by dabreegster** [comment]
> Now all tests from A/B Street pass.

Nice! It's great to see two new implementations, considerably simpler than the Rust version. I don't know if the existing tests are exhaustive. One idea for generating more cases is

1) I could port the Kotlin or Python implementation back to Rust
2) And run it on every single way in an area, comparing the two Rust implementations
3) When they differ, that means the original set of test cases wasn't exhaustive

I hope to have some time this week to do this. Does that sound like a useful next step for me?

**Comment by enzet** [comment]
> considerably simpler than the Rust version. I don't know if the existing tests are exhaustive.

Yeah, it was just test-driven. So I'll continue by writing new tests from real OSM ways and trying to support them.

> I could port the Kotlin or Python implementation back to Rust

Maybe you just extract your Rust implementation here? I'm sure my implementation is less reliable.

> Edit: or actually, just generate a JSON test case for every single way in an area using the Rust implementation. Then run the Python/Kotlin implementation against them, look for discrepancies, and boil down to the simplest test case

Yeah! This will do!
