### ISSUE TITLE
backward_outside can crash

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2lanes#107]
https://www.openstreetmap.org/way/200596577
`panicked at 'called `Option::unwrap()` on a `None` value', osm2lanes/src/transform/tags_to_lanes/mod.rs:418:80`
Relevant line is `let backward_edge = lane_to_edge_separator(self.backward_outside().unwrap());`

Start by adding a test case, then figure out what went wrong

**Comment by droogmic** [comment]
Closed by https://github.com/a-b-street/osm2lanes/pull/118, mostly accidentally.
