### ISSUE TITLE
attempt to subtract with overflow

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2lanes#152]
cargo run way 240294912
https://www.openstreetmap.org/way/240294912

osm2lanes/src/transform/tags_to_lanes/lane.rs:205:33

**Comment by droogmic** [comment]
`lanes:both_ways=2`, an odd one for sure, I don't even know what that means.

**Comment by dabreegster** [comment]
I think it's just a typo. https://wiki.openstreetmap.org/wiki/Key:lanes:both%20ways?uselang=en doesn't mention any other values. By and large, 1 is the value used https://taginfo.openstreetmap.org/keys/lanes%3Aboth_ways#values.

Should we
1) Throw an error
2) Assume any value besides "1" is a typo for "1" and emit a warning?
3) Assume any value besides "1" is a typo and not add anything?

I'll start with option 1 and at least not panic.

**Comment by droogmic** [comment]
My PR now implements the 3rd option, warning and ignore any value that
isn't 1.

**Comment by dabreegster** [comment]
Awesome, thank you! I'll add a test for this
