### ISSUE TITLE
Multiple Language Bindings and Implementations

### ISSUE THREAD

**Issue by droogmic** [a-b-street/osm2lanes#16]
At the time of writing, there is a python, kotlin, and rust implementation intending to cover the same functionality.

This issue tracks the development of a strategy on what language bindings and implementations to support, how to support them, and how to track their capabilities. (There were other discussions, but this is to regroup them).

**Comment by droogmic** [comment]
Maintaining 3 implementations may get tedious. Is there interest in using something like pyo3 to generate a python package from the rust implementation? With that it _should_ be possible to retain a nice object oriented API in python.

**Comment by dabreegster** [comment]
For the short-term, feel free to iterate on just the implementation of your choice. There's a `skip_rust`, `skip_python`, `skip_kotlin` field in the JSON test cases.

The original purpose of multiple languages was to make it as easy as possible to get contributors familiar with other languages -- even though hopefully the Rust one isn't touching any parts of the language that'd be hard to learn.

If we wanted to consolidate on a single language long-term, of course Rust gets my vote -- we can produce Python and Javascript bindings easily for sure, and a quick search shows JVM is also possible. But also, I think once we simplify the implementation, it should be fairly mechanical to port to another language and keep things in sync. The current Rust implementation is total spaghetti code, and the other two look cleaner so far.

One part of the maintenance burden is making all the enums -- if we switched to protobuf, we'd get those autogenerated for free. But there are other costs.

**Comment by enzet** [comment]
For me Python is more comfortable for prototyping (and of course because Map Machine is written in Python), so I started with it. I'm not sure why Kotlin is also here, I just wanted to try this language.

Anyway, since we want to use test-driven approach, fill free to support your preferred language and just use `skip_*` if implementations in other languages doesn't work on some test.

**Comment by droogmic** [comment]
After the conference, I would like to propose the following intermediate step:

Whilst rust tries to be feature complete, we can let python and kotlin only support a simpler subset of the schema:
- type
- designated
- direction

Still using the same test data and skipping mechanism?

**Comment by dabreegster** [comment]
A cost/benefit question: Who's going to catch the two implementations up? And is supporting 3 languages motivated by anyone wanting to contribute to the code but strongly preferring Python or Kotlin?

**Comment by droogmic** [comment]
I don't know. I don't mind just scrapping them entirely (we can always revive them later), but to not discourage contribution I wanted to at least reduce the gap.
