### ISSUE TITLE
Generate more test cases to cover the current Rust implementation

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2lanes#2]
The current test case suite lacks bus lanes, cycleway separators, and probably other cases. I can generate a JSON test case for every single OSM way in a region using the Rust implementation. Then run the Python/Kotlin implementation against them, look for discrepancies, and boil down to the simplest test cases.

**Comment by dabreegster** [comment]
https://github.com/a-b-street/abstreet/blob/master/cli/src/osm2lanes.rs is started. Output for Leeds (left-handed driving) and Seattle (right-handed) at https://gist.github.com/dabreegster/e6d67ab076e90d6ef95a9a9bce326590.

Before I boil down to simpler test cases, I guess we need to discuss the schema a bit more. I'll start another issue for that

**Comment by enzet** [comment]
Sorry, what? You just got 45 KLOC test? 😳

This is fantastic and a bit unexpected. 😆

**Comment by dabreegster** [comment]
No no, the huge example is just example output. I'll make up some new representative test cases from that. But before I do, I had some questions in #3 particularly about what we should do with the lane types.

**Comment by enzet** [comment]
Ah, OK. But it's still great. We just have to review parts of this generated file and extract new test out of it, right?

**Comment by dabreegster** [comment]
Right. One way to quickly filter is to run the Python or Kotlin implementation against all the tests and take a look at the failures. I should have time to do some of that tomorrow or Thursday

**Comment by enzet** [comment]
Yeah, looks good! I can take a look tomorrow too.

Funny thing is that it's already Wednesday in Moscow and my tomorrow is Thursday.

**Comment by dabreegster** [comment]
> Funny thing is that it's already Wednesday in Moscow and my tomorrow is Thursday.

There's some joke in the US about the west coast being lazy and waking up late. ;)   I'll be in a closer timezone to Moscow soon.

**Comment by enzet** [comment]
This is what I got from pytest:

```python
python/tests/test_lanes.py ....FFFFFFF..FF......................FFFFFF.. [  0%]
.....FFF...............FFFF.....FFF...F.........F....................... [  1%]
.........FFFF.......................FF.FFFFFFFFFFFFFFFF........FFFFFF..F [  1%]
FFF..............F.....................................FF..FFFF....F.... [  2%]
...............FFFFFF.FFF...FFFFFFFFFFFFF..........FFFFFF............... [  3%]
...........................F.....F...F........FF........FFFFF..........F [  4%]
..FFFFF..................F.....FFFFF................................FFFF [  4%]
FF.F.....F..............F...........FF...FFF........................FFF. [  5%]
FFFFF....FFFFFF............FF.........F....FF.FFFFFF..FFFF..F........... [  6%]
.........................................F.............................F [  7%]
FFFFFF..FF..FFFF..........F..............FF...F............F..FFF...F... [  7%]
........F.F.........FFF...........F..................F.......FF......... [  8%]
....F...F...FF.....F..F.F............................................... [  9%]
........................................................................ [ 10%]
............FFF..FFFFF.................................................. [ 10%]
```

**Comment by enzet** [comment]
First error:

```python
E         Expected: [shoulder ↑, driveway ↑, driveway ↑, driveway ↑]
E         Actual:   [shoulder ↑, driveway ↑, driveway ↑, driveway ↑, shoulder ↓]
E         Tags:
E             bicycle=yes
E             foot=yes
E             highway=trunk
E             horse=yes
E             junction=roundabout
E             lanes=3
E             lit=yes
E             motorcar=yes
E             oneway=yes
E             sidewalk=none
E             traffic_restriction=no_stopping
```

**Comment by dabreegster** [comment]
I don't think it's relevant anymore; we have tons of test coverage now
