### ISSUE TITLE
`sidewalk=separate` unsupported

### ISSUE THREAD

**Issue by Discostu36** [a-b-street/osm2lanes#249]
Ways that have a `sidewalk=separate` tag lead to a conversion error.

`Conversion Error: unsupported: 'sidewalk=separate' - osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs:213:32`

**Comment by BudgieInWA** [comment]
Good point. Like `sidewalk=no`, no sidewalk lanes should be generated for the way. osm2streets et al. should use `sidewalk=separate` to associate the nearby `highway=footway` or add a generic sidewalk as needed.

Maybe osm2lanes should gain an understanding of "parallel"/"adjacent" ways. Not to detect them, but to work with a list of them, the whole corridor, once they have been identified.
