### ISSUE TITLE
Web interface to convert tags to lanes

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2lanes#4]
We could have a simple webpage hosted on github pages where you copy in an OSM way's key/values, press a button, and get the JSON lanes output. Internally it can use Javascript and call the Rust implementation, compiled to WASM.

Next steps after that could be a Leaflet or Mapbox map, where you click on a way, we query Overpass for the nearest way and its tags, and do the same thing.

And then from there, maybe consider some kind of rendering/visualization, just for a single road.

**Comment by droogmic** [comment]
I had a go at this:
https://github.com/a-b-street/osm2lanes/pull/12

Helped me see that there is still quite a bit of edge-case handling missing.

**Comment by enzet** [comment]
I've tried to create some sketches. What do you think?

![road_signs](https://user-images.githubusercontent.com/2399987/148714526-e58f4bfe-ebef-498b-9f56-022cea50787c.png)

**Comment by dabreegster** [comment]
I think these are much more legible than Unicode, yeah! Maybe we could also print the width of each lane towards the bottom? We could also scale the width of each lane appropriately, but that stop being as legible in extreme cases

**Comment by droogmic** [comment]
> I've tried to create some sketches. What do you think?
> 
> ![road_signs](https://user-images.githubusercontent.com/2399987/148714526-e58f4bfe-ebef-498b-9f56-022cea50787c.png)

are you doing these in SVG? trying to think about how to render it...

**Comment by dabreegster** [comment]
If we can render each lane independently, then we could just lay them out in a row with HTML. Maybe the vertical lines in between get complicated, though... The output of the library doesn't explicitly tell you where bus and travel lanes border each other, or where the direction changes. But I guess that's easy enough to find by iterating over pairs of `LaneSpec`s...

**Comment by droogmic** [comment]
I think eventually we would want a lane spec that has more information.
e.g. width
e.g. dashed, solid, double lines
e.g. line colour
e.g. bicycle symbols, and their spacing...

a lot of these will not come from OSM tags but instead need to be contributed by users as they will specific to national and regional standards.

for now we can make some assumptions in the renderer, and make some assumptions when OSM tags are missing...

**Comment by enzet** [comment]
> are you doing these in SVG?

Yes, this is SVG.

> trying to think about how to render it...

I was thinking of creating SVG canvas in the HTML page and add SVG elements to it using JS. I'm not quite experienced in JS so not sure it is the right way to do this.
