### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by tordans** [a-b-street/osm2lanes#48]
The readme states 

> This repo is currently just for starting this experiment. No license chosen yet.

https://github.com/a-b-street/osm2lanes#osm2lanes

---

I just wanted to add this issue to not miss the point when the experiment becomes a project that should have a license …

**Comment by dabreegster** [comment]
Good point! Probably time to decide this.

I don't know too much about licensing, but in the Rust world, it's standard for libraries to dual-license under Apache and MIT: https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license. I propose doing the same.

@enzet and @droogmic, any opinion? Once we agree, we can choose it

**Comment by tordans** [comment]
Just two thoughts…

---

iD uses https://github.com/openstreetmap/iD/blob/develop/LICENSE.md and the short summary on that page sounds good; its also super open, comparing it to https://github.com/openstreetmap/openstreetmap-website/blob/master/LICENSE

---

The dual license sounds a bit complex and breaks tooling like the licence-check in Github since that is optimized for just one license. Eg for https://github.com/dtolnay/rust-faq the sidebar only links to the Apache file but without the summary header and only [the commit hints at](https://github.com/dtolnay/rust-faq/commit/8070c0cf3f51b82ff15f01ce5bfa1eb25ae52b3c) the second MIT file.

**Comment by droogmic** [comment]
I known enough about open source licensing to know I don't know enough to comment..., sorry.

**Comment by enzet** [comment]
MIT or Apache look good to me.  Anyway, I am happy with any open source license.

**Comment by dabreegster** [comment]
Any opposition to Apache?

**Comment by enzet** [comment]
From my side, no. Apache looks good.

**Comment by droogmic** [comment]
looks good
