### ISSUE TITLE
Website Slippy Map

### ISSUE THREAD

**Issue by droogmic** [a-b-street/osm2lanes#64]
The website https://a-b-street.github.io/osm2lanes/ has a "OSM Way ID", but it would be easier to select this from a slippy map.

**Comment by droogmic** [comment]
As mentioned by @dabreegster , but I don't really know how to approach this.

**Comment by dabreegster** [comment]
A simple idea to start -- use a normal slippy map, add a click handler that gives the lat,lng clicked, feed that into Overpass and look for road-like ways nearby (with the [around](https://stackoverflow.com/questions/16442663/how-to-get-point-of-interest-near-my-point-using-overpass-api) modifier?), have the rest of the web interface below that.

With MapboxGL, getting clicks is easy: https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures-around-point/
Leaflet also exposes an on-click event: https://leafletjs.com/reference.html#map-event

**Comment by tordans** [comment]
I can help with that if it's OK to have it simple JS + HTML. Will need/take a few days, though. First idea: I was thinking about a two-frame-solution where there is a separate map left and on click the right frame with the https://a-b-street.github.io/osm2lanes/ UI shows up. The UI at https://a-b-street.github.io/osm2lanes/ would need to have an option to take the way-ID via URL param.

**Comment by droogmic** [comment]
> would need to have an option to take the way-ID via URL param

This can probably done with a yew router: https://yew.rs/docs/concepts/router

**Comment by dabreegster** [comment]
We now have this in a vanilla JS version: https://github.com/a-b-street/osm2lanes/blob/main/web/index.html
It'd be nice to combine the two still. Should we add some kind of hideable Mapbox panel in the yew version?

**Comment by droogmic** [comment]
And we now have a version on the website thanks to https://github.com/a-b-street/osm2lanes/pull/124
