### ISSUE TITLE
Rename `driveway` to `travel_lane`

### ISSUE THREAD

**Issue by enzet** [a-b-street/osm2lanes#8]

**Comment by dabreegster** [comment]
Any initial thoughts on distinguishing travel lanes from turn lanes? This issue is about a mechanical rename, but it's something I've been thinking about. Alternatively turn lanes could be an option underneath the travel_lane type.

**Comment by enzet** [comment]
Initially I thought that for a bus lanes and turn lanes we should use Boolean flags on `travel_lane`. But now I'm confused. @kfarr mentioned, they use `drive-lane`, `turn-lane`, and `bus-lane` types. Now I think, separate lanes is better choice. To be honest I just don't know.
